services:
  gremlin:
    hostname: gremlin
    container_name: gremlin
    image: tinkerpop/gremlin-server:3.7.3
    volumes:
      - ./gremlin-server:/opt/gremlin-server/conf
      - graph-data:/opt/gremlin-server/data
    ports:
      - "8182:8182"
    user: "0:0"  # Run as root
volumes:
  graph-data:
